# Generated by Django 5.1.3 on 2024-11-22 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ott', '0002_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='seasons',
        ),
        migrations.AddField(
            model_name='movie',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='single_movies', to='ott.video'),
        ),
        migrations.AlterField(
            model_name='season',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='ott.movie'),
        ),
    ]
