# Generated by Django 5.1.3 on 2024-11-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ott', '0003_remove_movie_seasons_movie_videos_alter_season_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
